class codes:
    instruction_on = 1
    instruction_off = 2
    fixation_on = 3
    fixation_off = 4
    dots_left_on = 5
    dots_right_on = 6
    dots_off = 7
    response_left_correct = 8
    response_left_incorrect = 9
    response_right_correct = 10
    response_right_incorrect = 11
    feedback_noResponse_on = 12
    feedback_correct_on = 13
    feedback_incorrect_on = 14
    feedback_inTime_on = 15
    feedback_tooSlow_on = 16
    feedback_off = 17
    endBlockInstructions_on = 18
    endBlockInstructions_off = 19
    continueBlockResponse = 20
    dots_left_on_5 = 21
    dots_left_on_10 = 22
    dots_left_on_15 = 23
    dots_left_on_25 = 24
    dots_left_on_35 = 25
    dots_left_on_50 = 26
    dots_left_on_100 = 27
    dots_right_on_5 = 28
    dots_right_on_10 = 29
    dots_right_on_15 = 30
    dots_right_on_25 = 31
    dots_right_on_35 = 32
    dots_right_on_50 = 33
    dots_right_on_100 = 34
#    def __init__(self):
        # do nothing
    
